# Generated by Django 4.2.11 on 2024-03-19 19:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CheeseBoardSite", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="accountCreationDate",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 3, 19, 19, 52, 1, 573868, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="dateLastLoggedIn",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 3, 19, 19, 52, 1, 573868, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="dateOfBirth",
            field=models.DateField(
                default=datetime.datetime(2024, 3, 19, 19, 52, 1, 573869)
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="followers",
            field=models.ManyToManyField(
                blank=True, null=True, to="CheeseBoardSite.account"
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="following",
            field=models.ManyToManyField(
                blank=True, null=True, to="CheeseBoardSite.account"
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="timeDate",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 3, 19, 19, 52, 1, 576868, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="timeDate",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 3, 19, 19, 52, 1, 575368, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
