# Generated by Django 2.2.28 on 2024-03-20 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CheeseBoardSite', '0010_auto_20240320_1356'),
        ('CheeseBoardSite', '0003_auto_20240320_0108'),
    ]

    operations = [
    ]
