# Generated by Django 2.2.28 on 2024-03-18 13:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('CheeseBoardSite', '0012_auto_20240318_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='cheese',
            name='slug',
            field=models.SlugField(default='slug', unique=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='accountCreationDate',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 18, 13, 4, 40, 840347, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='account',
            name='dateLastLoggedIn',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 18, 13, 4, 40, 840347, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='account',
            name='dateOfBirth',
            field=models.DateField(default=datetime.datetime(2024, 3, 18, 13, 4, 40, 840347)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='timeDate',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 18, 13, 4, 40, 843335, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='timeDate',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 18, 13, 4, 40, 842340, tzinfo=utc)),
        ),
    ]
